name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
      - name: Setup Maven caching
        uses: actions/cache@v2
        with:
          path: ~/.m2/**
          key: maven_deps
      - name: Build and test
        run: mvn clean test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image (CI)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false # Set to true to push the image to a registry
          tags: sokomishalov:skraper
          # You might need to add a 'file' input if your Dockerfile is not named Dockerfile
          # file: ./path/to/Dockerfile
          # Add login step here if pushing
          # login_server: docker.io
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}